name: pet
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  english_words: ^4.0.0
  flutter_svg: ^1.1.6
  flutter_staggered_grid_view: ^0.6.2
  audioplayers: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/

  fonts:
    - family: Airbnb
      fonts:
        - asset: fonts/AirbnbCereal_W_Bd.otf
          weight: 700
    - family: Helvetica-Neue
      fonts:
        - asset: fonts/Helvetica-Neue-2.ttf