// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJL2Fi9XzZm_R-0QjOgVd5JpijxTqf4yw',
    appId: '1:437873685944:web:e67f4b991c1c94880e0b4d',
    messagingSenderId: '437873685944',
    projectId: 'coina-sienava',
    authDomain: 'coina-sienava.firebaseapp.com',
    storageBucket: 'coina-sienava.appspot.com',
    measurementId: 'G-06BSFB2EYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFhVeiBe4cgDEDH1o0T12-mx_Y4YM5FJE',
    appId: '1:437873685944:android:d3042e2211a3b0570e0b4d',
    messagingSenderId: '437873685944',
    projectId: 'coina-sienava',
    storageBucket: 'coina-sienava.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAk3VQAR0pk81kHaKJ2_qVJcXLfnP2S_Y',
    appId: '1:437873685944:ios:bb671e9043c5023e0e0b4d',
    messagingSenderId: '437873685944',
    projectId: 'coina-sienava',
    storageBucket: 'coina-sienava.appspot.com',
    iosClientId: '437873685944-72f4dbqvt7ghvhhbgq3o616ffrp7er3f.apps.googleusercontent.com',
    iosBundleId: 'com.example.coina',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAk3VQAR0pk81kHaKJ2_qVJcXLfnP2S_Y',
    appId: '1:437873685944:ios:bb671e9043c5023e0e0b4d',
    messagingSenderId: '437873685944',
    projectId: 'coina-sienava',
    storageBucket: 'coina-sienava.appspot.com',
    iosClientId: '437873685944-72f4dbqvt7ghvhhbgq3o616ffrp7er3f.apps.googleusercontent.com',
    iosBundleId: 'com.example.coina',
  );
}
